website/models.py
from flask_login import UserMixin

class User(UserMixin):
    def __init__(self, data):
        self.id = data[0]
        self.name = data[1]
        self.lastname = data[2]
        self.email = data[3]
        self.password = data[4]

website/__init__.py
from flask import Flask
from flask_login import LoginManager
import requests

# url = 'http://44.195.223.194:8000/'
url = 'http://3.214.121.253:8005/'
url2 = 'http://3.214.121.253:8000/'

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'testkey'

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User

    @login_manager.user_loader
    def load_user(id):
        response = requests.get(f'{url2}userid/{id}')
        if response.status_code == 200:
            response_data = response.json()
            if response_data:
                return User(data=response_data[0])
        return

    return app

website/auth.py
import requests
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from .models import User
from .__init__ import url, url2

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        data = {
            'email': email,
            'password_hash': password
        }
        response = requests.get(f'{url2}user', data=data)
        if response.status_code == 200:
            flash('Logged in succesfully!', category='success')
            response_data = response.json()
            if response_data:
                login_user(User(response_data[0]), remember=True)
                return redirect(url_for('views.home'))
        flash("Incorrect email or password, try again.", category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        name = request.form.get('name')
        lastname = request.form.get('lastname')
        email = request.form.get('email')
        password = request.form.get('password')

        data = {
            'name':name,
            'lastname':lastname,
            'email':email,
            'password_hash':password
        }
        response = requests.post(f'{url}users', data=data)
        if response.status_code == 200:
            flash('Account created, enter now!', category='success')
            return redirect(url_for('auth.login'))
        else:
            flash("Failed to add user.", category='error')
            
    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .__init__ import url, url2
import requests

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        user_id = current_user.id
        title = request.form.get('title')
        description = request.form.get('description')
        data ={
            "title": title,
            "description": description
        }
        print(data)
        print(f'{url}user/{user_id}')        
        response = requests.post(f'{url}user/{user_id}', data=data)
        if response.status_code == 200:
            flash('Goal added succesfully!', category='success')
            response_data = response.json()
        else:
            flash("Error: Goal not added, try again.", category='error')

        return redirect(url_for('views.home'))

    goals = []
    response = requests.get(f'{url}user/{current_user.id}')
    if response.status_code == 200:
        response_data = response.json()
        if response_data:
            goals = response_data
    print(goals)
    return render_template("home.html", user=current_user, goals=goals)

@views.route('goal/delete/<int:goal_id>', methods=['POST'])
@login_required
def delete(goal_id):
    response = requests.delete(f'{url}goal/{goal_id}')
    if response.status_code == 200:
        flash('Goal deleted succesfully!', category='success')
    else:
        flash('Failed to delete goal.', category='error')
    
    return redirect(url_for('views.home'))

@views.route('/goal/edit/<int:goal_id>', methods=['GET', 'POST'])
@login_required
def edit(goal_id):
    response = requests.get(f'{url}goal/{goal_id}')
    goal = response.json()
    print(goal)

    if request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')
        data = {
            "title": title,
            "description": description,
            "is_completed": 0
        }
        print(data)
        print(f'{url}goal/{goal[0]}')        
        response = requests.put(f'{url}goal/{goal_id}', data=data)
        if response.status_code == 200:
            flash('Goal updated successfully.', category='success')
        else:
            flash('Failed to update goal.', category='error')
        return redirect(url_for('views.home'))

    return render_template("goal.html", user=current_user, goal=goal)

@views.route('/comments/<int:goal_id>', methods=['GET', 'POST'])
@login_required
def comments(goal_id):
    response = requests.get(f'{url}goal/{goal_id}')
    goal = response.json()
    print(goal)
    if request.method == 'POST':
        content = request.form.get('content')
        user_id = current_user.id
        data = {
            "content":content,
            "user_id":user_id,
            "goal_id":goal_id
        }
        print(data)
        print(f'{url2}comment')        
        response = requests.post(f'{url2}comment', data=data)
        if response.status_code == 200:
            flash('Comment added successfully!', category='success')
            response_data = response.json()
        else:
            flash("Failed to add comment.", category='error')
    
        return redirect(url_for('views.comments', goal_id=goal_id))

    comments = []
    response = requests.get(f'{url2}comments/{goal_id}')
    if response.status_code == 200:
        response_data = response.json()
        if response_data:
            comments = response_data
    print(comments)
    return render_template("comments.html", user=current_user, goal=goal, comments=comments)

@views.route('/comment/edit/<int:comment_id>', methods=['GET', 'POST'])
@login_required
def edit_comment(comment_id):
    response = requests.get(f'{url2}comment',data={"comment_id":comment_id})
    comment = response.json()
    print(comment)

    if request.method == 'POST':
        content = request.form.get('content')
        data = {
            "content": content,
            "comment_id": comment_id
        }
        print(data)
        print(f'{url2}comment/')        
        response = requests.put(f'{url2}comment', data=data)
        if response.status_code == 200:
            flash('Comment updated successfully.', category='success')
        else:
            flash('Failed to update comment.', category='error')
        return redirect(url_for('views.home'))

    return render_template("comment.html", user=current_user, comment=comment)

@views.route('/comment/delete/<int:comment_id>', methods=['POST'])
@login_required
def delete_comment(comment_id):
    response = requests.delete(f'{url2}comment', data={"comment_id": comment_id})
    if response.status_code == 200:
        flash('Comment deleted succesfully!', category='success')
    else:
        flash('Failed to delete comment.', category='error')
    
    return redirect(url_for('views.home'))

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous"
        />
    
        <title>{% block title %}Home{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbar"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" id="home" href="/">Home</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %}
          {% for category, message in messages %}
          {% if category == 'error' %}
          <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% else %}
          <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}


        <div class="container">{% block content %} {% endblock %}</div>
        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
        ></script>

        <script
            type="text/javascript"
            src="{{ url_for('static', filename='index.js')}}"
        ></script>


    </body>
</html>

website/templates/comment.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}

{% for c in comment %}
<form method="POST">
    <h1 align="center">Editar comentario</h1>
    <label for="content">Content:</label>
    <textarea name="content" id="content" placeholder="Ingresa tu comentario" class="form-control">{{c[1]}}</textarea>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-primary">Finish</button>
    </div>
    <br/>
</form>
{% endfor %}

{% endblock %}

website/templates/comments.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}

{% for g in goal %}
<h1 align="center">{{ g[1] }}</h1>
<h3 align="center">{{ g[2] }}</p>
<br/><br/>

{% for c in comments %}
<li class="list-group-item">
    <h4>{{ c[1] }}</h4>
    {{ c[2] }}
    <br/><br/>
    {% if user.id == c[3] %}
    <a href="{{ url_for('views.edit_comment', comment_id=c[0]) }}">
        <button class="btn btn-info">Edit</button>
    </a>
    <form method="post" style="display:inline-block" action="{{ url_for('views.delete_comment', comment_id=c[0]) }}">
        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
    </form>
    {% endif %}
</li>
{% endfor %}
<form method="POST">
    <h1 align="center">Añadir comentario</h1>
    <label for="content">Cotenido:</label>
    <textarea name="content" id="content" placeholder="Ingresa tu comentario" class="form-control"></textarea>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    <br/>
</form>
{% endfor %}

{% endblock %}

website/templates/goal.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}

{% for g in goal %}
<form method="POST">
    <h1 align="center">{{ g[1] }}</h1>
    <label for="title">Title:</label>
    <textarea name="title" id="title" placeholder="Ingresa tu titulo" class="form-control">{{g[1]}}</textarea>
    <br/>
    <label for="description">Description:</label>
    <textarea name="description" id="description" placeholder="Ingresa tu descripcion" class="form-control">{{g[2]}}</textarea>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-primary">Finish</button>
    </div>
    <br/>
</form>
{% endfor %}

{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}

<h1 align="center">Goals</h1>
<ul class="list-group list-group-flush" id="goals">
    <h3>Your goals:</h3>
    {% for goal in goals %}
    <li class="list-group-item">
        <h4>{{goal[1]}}</h4>
        {{goal[2]}}
        <br/><br/>
        <a href="{{ url_for('views.edit', goal_id=goal[0]) }}">
            <button class="btn btn-info">Edit</button>
        </a>
        <form method="post" style="display:inline-block" action="{{ url_for('views.delete', goal_id=goal[0])}}">
            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
        </form>
        <a href="{{ url_for('views.comments', goal_id=goal[0]) }}">
            <button class="btn btn-secondary">Comments</button>
        </a>
    </li>
    {% endfor %}
</ul>
<br/>
<form method="POST">
    <h3>Add a new Goal!</h3>
    <label for="title">Title:</label>
    <textarea name="title" id="title" placeholder="Goal title" class="form-control"></textarea>
    <br/>
    <label for="description">Description:</label>
    <textarea name="description" id="description" placeholder="Describe your goal" class="form-control"></textarea>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-primary">Add Goal</button>
    </div>
    <br/>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="name">Email</label>
        <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter email"
        />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter password"
        />
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="name">Name</label>
        <input
            type="text"
            class="form-control"
            id="name"
            name="name"
            placeholder="Enter name"
        />
    </div>
    <div class="form-group">
        <label for="name">Last Name</label>
        <input
            type="text"
            class="form-control"
            id="lastname"
            name="lastname"
            placeholder="Enter lastname"
        />
    </div>
    <div class="form-group">
        <label for="name">Email</label>
        <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter email"
        />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter password"
        />
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}